language: node_js
sudo: false
branches:
  except:
    - develop
script: npm run cover
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - stable
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: freeformsystems@gmail.com
  api_key:
    secure: CXGz1uj14rCc6FTlYnVNm9LN7DPukLBZ9fvlX+FO5THPzkPmnxOTrfYKw9Mk7anguAF2rE5D9AZXU1zOWPT8C8wkcPsIu4m3NdxFF/V1DAsU7hu2x00tUAw/JapNHPee/EKuHiAMOvgTwN0uiKdYBFAF4efkFiJ23Oawvjl+P9Y5DRRijPF52jB2jhv+GqPZyx1Z3cbwKhzO3gju2MRdSd2djStr05DzHP78QOt/7dJBNibs70WhiiH5zJ92IvXu3BaAhNq2nUCUEnGaHg7kJkU+YWzBcw4jQFHVbyB8dS3tnI+/b2sdBUYh4hgOTytG+UVeBK/afBhmHpWxEU0YNtnw1/Ek3/UAe4hVggf2SA8XAaywntR84WnYgeLItJMy7mrhWSWynmoVW9ZAKO8sg7F2WbIrXYhEuGmjkSN4R40I6ndEqxbTNVDnGGDeWrWgugZ2IxjSpFrTzEqz+Skt6eI8mf2MtsMHUuzctkxuMlf8WWWeVwu1z0L4YVj4lVSj6R2h12c4cqDJcad7FxuuJm+35F4B5CzOVoG3W0FDva0ZTuPYJu6d9WSPJAPd/vRn42dUmIdqzP5J9jQP6k+EM/xH0UyK5nxsg9E3DX+wTjX+wwJ8OAXIx/AfFYClV9UEL4Lle7GuHMFOgLoZ7jiK19oN4EKIP4+uV2IDowsiRZE=
  on:
    tags: true
    repo: tmpfs/cparse
    node: '4.1'
